### ISSUE TITLE
The package can't be installed because it is not signed

### ISSUE THREAD

**Issue by intelligear** [lomorage/LomoAgentOSX#1]
Error:
> “LomoAgent” cannot be opened because the developer cannot be verified.
> macOS cannot verify that this app is free from malware.

Running MacOS 12.2

**Comment by fuji246** [comment]
Some 3rd party need recompile and sign. You can go to "System Preference" -> "Security & Privacy" to unblock it as a workaround for now.

**Comment by fuji246** [comment]
fixed in latest release
